export { default as BinanceWalletIcon } from './BinanceWalletIcon'
export { default as MathWalletIcon } from './MathWalletIcon'
export { default as MetamaskIcon } from './MetamaskIcon'
export { default as SafepalIcon } from './SafepalIcon'
export { default as TokenPocketIcon } from './TokenPocketIcon'
export { default as TrustWalletIcon } from './TrustWalletIcon'
export { default as WalletConnectIcon } from './WalletConnectIcon'
