export { default as FacebookIcon } from './FacebookIcon'
export { default as GithubIcon } from './GithubIcon'
export { default as MediumIcon } from './MediumIcon'
export { default as TelegramIcon } from './TelegramIcon'
export { default as TwitterIcon } from './TwitterIcon'
